### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown URL

### ISSUE THREAD

**Issue by okatticus** [okatticus/Noted#1]
**The error log from android studio:**
06-30 10:47:17.942 5425-5425/com.example.android.noted E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.example.android.noted, PID: 5425
                                                                         java.lang.RuntimeException: Unable to pause activity {com.example.android.noted/com.example.android.noted.NotedDetailActivity}: java.lang.IllegalArgumentException: Unknown URL  content://com.example.android.noted.contentprovider/noted
                                                                             at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3064)
                                                                             at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3019)
                                                                             at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2997)
                                                                             at android.app.ActivityThread.access$1000(ActivityThread.java:141)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1229)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: java.lang.IllegalArgumentException: Unknown URL  content://com.example.android.noted.contentprovider/noted
                                                                             at android.content.ContentResolver.insert(ContentResolver.java:1199)
                                                                             at com.example.android.noted.NotedDetailActivity.saveState(NotedDetailActivity.java:108)
                                                                             at com.example.android.noted.NotedDetailActivity.onPause(NotedDetailActivity.java:92)
                                                                             at android.app.Activity.performPause(Activity.java:5346)
                                                                             at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1233)
                                                                             at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3050)
                                                                             at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3019) 
                                                                             at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2997) 
                                                                             at android.app.ActivityThread.access$1000(ActivityThread.java:141) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1229) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 

**The error probably  is with Content Authority (URI)**

**Comment by okatticus** [comment]
Fixed it.
